Testing geobase

diff --git a/.github/workflows/scan.yml b/.github/workflows/scan.yml
--- a/.github/workflows/scan.yml
+++ b/.github/workflows/scan.yml
@@ -1,39 +1,122 @@
 name: Scan
 
 on: [push, pull_request]
-
+env:
+  BUILDER_IMAGE_NAME: opendatacube/geobase:builder
+  RUNNER_IMAGE_NAME: opendatacube/geobase:runner
+  RUNNER_IMAGE_NAME: opendatacube/geobase:wheels
 jobs:
-  vuln-scan:
+  cve-scanner:
     runs-on: ubuntu-latest
-    steps:
+# Builder
+      - name: pull the images
+        id: builder_docker_pull
+        run: |
+          docker pull "${{ env.BUILDER_IMAGE_NAME }}"
+
       - name: Run vulnerability scanner
+        if: github.event_name != 'release'
         uses: aquasecurity/trivy-action@0.0.8
         continue-on-error: true
-        id: runner
+        id: builder_scan
         with:
-          image-ref: opendatacube/ows:1.8.2-89-g995e340
+          image-ref: "${{ env.BUILDER_IMAGE_NAME }}"
           format: "template"
           template: '@/contrib/gitlab.tpl'
           output: 'trivy-results.json'
           severity: "CRITICAL,HIGH"
 
       - name: Read trivy-results
-        id: package
+        id: builder_package
         uses: juliangruber/read-file-action@v1
         with:
           path: ./trivy-results.json
 
       - name: Notify Slack for Failures
-        uses: rtCamp/action-slack-notify@v2.1.2
+        uses: rtCamp/action-slack-notify@v2.1.0
         if: steps.runner.outcome != 'success'
-        id: slack
+        id: builder_slack
         env:
           SLACK_CHANNEL: ga-wms-ops
           SLACK_ICON: "https://github.com/docker.png?size=48"
           SLACK_COLOR: "#482de1"
           SLACK_MESSAGE: ${{join(steps.package.outputs.content, '\n')}}
           SLACK_TITLE: CVE Scan alert
-          SLACK_USERNAME: datacube-ows scanner
+          SLACK_USERNAME: GEOBASE Scanner
+          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+# Runner
+    steps:
+      - name: pull the images
+        id: runner_docker_pull
+        run: |
+          docker pull "${{ env.RUNNER_IMAGE_NAME }}"
+
+      - name: Run vulnerability scanner
+        if: github.event_name != 'release'
+        uses: aquasecurity/trivy-action@0.0.8
+        continue-on-error: true
+        id: runner_scan
+        with:
+          image-ref: "${{ env.RUNNER_IMAGE_NAME }}"
+          format: "template"
+          template: '@/contrib/gitlab.tpl'
+          output: 'trivy-results.json'
+          severity: "CRITICAL,HIGH"
+
+      - name: Read trivy-results
+        id: runner_package
+        uses: juliangruber/read-file-action@v1
+        with:
+          path: ./trivy-results.json
+
+      - name: Notify Slack for Failures
+        uses: rtCamp/action-slack-notify@v2.1.0
+        if: steps.runner.outcome != 'success'
+        id: runner_slack
+        env:
+          SLACK_CHANNEL: ga-wms-ops
+          SLACK_ICON: "https://github.com/docker.png?size=48"
+          SLACK_COLOR: "#482de1"
+          SLACK_MESSAGE: ${{join(steps.package.outputs.content, '\n')}}
+          SLACK_TITLE: CVE Scan alert
+          SLACK_USERNAME: GEOBASE Scanner
+          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+
+# Wheels
+      - name: pull the images
+        id: wheels_docker_pull
+        run: |
+          docker pull "${{ env.WHEELS_IMAGE_NAME }}"
+
+      - name: Run vulnerability scanner
+        if: github.event_name != 'release'
+        uses: aquasecurity/trivy-action@0.0.8
+        continue-on-error: true
+        id: wheels_scan
+        with:
+          image-ref: "${{ env.WHEELS_IMAGE_NAME }}"
+          format: "template"
+          template: '@/contrib/gitlab.tpl'
+          output: 'trivy-results.json'
+          severity: "CRITICAL,HIGH"
+
+      - name: Read trivy-results
+        id: wheels_package
+        uses: juliangruber/read-file-action@v1
+        with:
+          path: ./trivy-results.json
+
+      - name: Notify Slack for Failures
+        uses: rtCamp/action-slack-notify@v2.1.0
+        if: steps.runner.outcome != 'success'
+        id: wheels_slack
+        env:
+          SLACK_CHANNEL: ga-wms-ops
+          SLACK_ICON: "https://github.com/docker.png?size=48"
+          SLACK_COLOR: "#482de1"
+          SLACK_MESSAGE: ${{join(steps.package.outputs.content, '\n')}}
+          SLACK_TITLE: CVE Scan alert
+          SLACK_USERNAME: GEOBASE Scanner
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
 
       - name: steps
@@ -42,40 +125,91 @@ jobs:
           STEPS_CONTEXT: ${{ toJson(steps) }}
         run: echo "$STEPS_CONTEXT"
 
-      - name: Check on failures
-        if: steps.runner.outcome != 'success'
-        run: exit 1
-
-      # - name: Run vulnerability scanner
-      #   uses: aquasecurity/trivy-action@0.0.8
-      #   continue-on-error: true
-      #   with:
-      #     image-ref: opendatacube/ows:1.8.2-89-g995e340
-      #     format: 'template'
-      #     template: '@/contrib/sarif.tpl'
-      #     output: 'trivy-results.sarif'
-      #     exit-code: "1"
-      #     severity: "CRITICAL,HIGH"
-
-      # - name: Upload Trivy scan results to GitHub Security tab
-      #   uses: github/codeql-action/upload-sarif@v1
-      #   with:
-      #     sarif_file: 'trivy-results.sarif'
-
-      # - name: Notify Slack for Failures
-      #   uses: rtCamp/action-slack-notify@v2.1.0
-      #   # if: failure()
-      #   env:
-      #     SLACK_CHANNEL: ga-wms-ops
-      #     SLACK_ICON: "https://github.com/docker.png?size=48"
-      #     SLACK_COLOR: "#482de1"
-      #     SLACK_MESSAGE: ""
-      #     SLACK_TITLE: CVE Scan alert
-      #     SLACK_USERNAME: datacube-ows scanner
-      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+      # - name: Check on failures
+      #   if: steps.runner.outcome != 'success'
+      #   run: exit 1
 
 
+# name: Scan
 
+# on: [push, pull_request]
+
+# jobs:
+#   vuln-scan:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Run vulnerability scanner
+#         uses: aquasecurity/trivy-action@0.0.8
+#         continue-on-error: true
+#         id: runner
+#         with:
+#           image-ref: opendatacube/ows:1.8.2-89-g995e340
+#           format: "template"
+#           template: '@/contrib/gitlab.tpl'
+#           output: 'trivy-results.json'
+#           severity: "CRITICAL,HIGH"
+
+#       - name: Read trivy-results
+#         id: package
+#         uses: juliangruber/read-file-action@v1
+#         with:
+#           path: ./trivy-results.json
+
+#       - name: Notify Slack for Failures
+#         uses: rtCamp/action-slack-notify@v2.1.2
+#         if: steps.runner.outcome != 'success'
+#         id: slack
+#         env:
+#           SLACK_CHANNEL: ga-wms-ops
+#           SLACK_ICON: "https://github.com/docker.png?size=48"
+#           SLACK_COLOR: "#482de1"
+#           SLACK_MESSAGE: ${{join(steps.package.outputs.content, '\n')}}
+#           SLACK_TITLE: CVE Scan alert
+#           SLACK_USERNAME: datacube-ows scanner
+#           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+
+#       - name: steps
+#         id: steps_id
+#         env:
+#           STEPS_CONTEXT: ${{ toJson(steps) }}
+#         run: echo "$STEPS_CONTEXT"
+
+#       - name: Check on failures
+#         if: steps.runner.outcome != 'success'
+#         run: exit 1
+
+#       # - name: Run vulnerability scanner
+#       #   uses: aquasecurity/trivy-action@0.0.8
+#       #   continue-on-error: true
+#       #   with:
+#       #     image-ref: opendatacube/ows:1.8.2-89-g995e340
+#       #     format: 'template'
+#       #     template: '@/contrib/sarif.tpl'
+#       #     output: 'trivy-results.sarif'
+#       #     exit-code: "1"
+#       #     severity: "CRITICAL,HIGH"
+
+#       # - name: Upload Trivy scan results to GitHub Security tab
+#       #   uses: github/codeql-action/upload-sarif@v1
+#       #   with:
+#       #     sarif_file: 'trivy-results.sarif'
+
+#       # - name: Notify Slack for Failures
+#       #   uses: rtCamp/action-slack-notify@v2.1.0
+#       #   # if: failure()
+#       #   env:
+#       #     SLACK_CHANNEL: ga-wms-ops
+#       #     SLACK_ICON: "https://github.com/docker.png?size=48"
+#       #     SLACK_COLOR: "#482de1"
+#       #     SLACK_MESSAGE: ""
+#       #     SLACK_TITLE: CVE Scan alert
+#       #     SLACK_USERNAME: datacube-ows scanner
+#       #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+
+
+# name: Scan
+
+# on: [push, pull_request]
 # env:
 #   RUNNER_IMAGE_NAME: opendatacube/geobase:runner
 # jobs:
